<script setup lang="ts">
import { ref, computed } from 'vue'
import type { Ref } from 'vue'
import JSZip from 'jszip'
import { saveAs } from 'file-saver'

import GameInfo from './GameInfo.vue'
import SetInfo from './SetInfo.vue'
import GameBox from './GameBox.vue'
import ZipPreviewPane from './ZipPreviewPane.vue'
import RecentDrafts from './RecentDrafts.vue'
import DiscordMessage from './DiscordMessage.vue'
import type { ReplayMetadata, ReplayErrors } from '../entities/gamemeta'

import { Game, Replay, zipFilename, computeReplayFilename } from '../entities/game'
import { extractDraftUrl } from '../entities/draft'

const props = defineProps<{
  civPresets: string[] | null
  mapPresets: string[] | null
}>()

const player1 = ref('Player1')
const player2 = ref('Player2')
const boPa = ref<'best-of' | 'play-all'>('best-of')
const mapDraft: Ref<string> = ref('')
const civDraft: Ref<string> = ref('')
const games: Ref<Game[]> = ref([new Game(), new Game(), new Game()])
const meta: Ref<ReplayMetadata> = ref({ maps: null, civs: null })
const metaErrors: Ref<ReplayErrors> = ref({ maps: null, civs: null })

function removeReplay(gameIdx: number, replayIdx: number) {
  games.value[gameIdx].replays.splice(replayIdx, 1)
  if (games.value[gameIdx].replays.length == 0) {
    games.value.splice(gameIdx, 1)
  }
}

function addReplay(gameIdx: number) {
  games.value[gameIdx].replays.push(new Replay())
}

function updateReplay(gameIdx: number, replayIdx: number, file: File | null) {
  games.value[gameIdx].replays[replayIdx].file = file
}

function addGame() {
  games.value.push(new Game())
}

function setGames(gamesNumber: number) {
  while (games.value.length < gamesNumber) {
    addGame()
  }
  if (games.value.length > gamesNumber) {
    games.value = games.value.slice(0, gamesNumber)
  }
}

const downloadWarning = computed(() => {
  if (boPa.value == 'best-of') {
    return false
  }

  for (const game of games.value) {
    for (const replay of game.replays) {
      if (!replay.file) {
        return true
      }
    }
  }

  return false
})

const downloadEnabled = computed(() => {
  if (metaErrors.value.civs || metaErrors.value.maps) {
    return false
  }

  // Force civ draft entry if preset is specified
  /*if (props.civPresets && !meta.value.civs) {
    return false
  }*/

  // Force map draft entry if preset is specified
  /*if (props.mapPresets && !meta.value.maps) {
    return false
  }*/

  for (const game of games.value) {
    for (const replay of game.replays) {
      if (replay.file) {
        return true
      }
    }
  }
  return false
})

function getFirstReplayFile(): File | null {
  for (const game of games.value) {
    for (const replay of game.replays) {
      if (replay.file) {
        return replay.file
      }
    }
  }
  return null
}

function getRandomInt(min: number, max: number) {
  const minCeiled = Math.ceil(min)
  const maxFloored = Math.floor(max)
  return Math.floor(Math.random() * (maxFloored - minCeiled) + minCeiled) // The maximum is exclusive and the minimum is inclusive
}

function downloadZip() {
  const zip = new JSZip()
  const zipComment = 'Generated by https://zetatwo.github.io/aoe2replaypacker'

  const dummyBase = getFirstReplayFile()
  if (!dummyBase) {
    console.log('Could not find any valid replay files')
    return
  }

  for (const [gameIdx, game] of games.value.entries()) {
    for (const [replayIdx, replay] of game.replays.entries()) {
      const replay_filename = computeReplayFilename(
        player1.value,
        player2.value,
        game,
        gameIdx,
        replayIdx
      )
      if (replay.file) {
        zip.file(replay_filename, replay.file)
      } else {
        const suffixArray = new Uint8Array(getRandomInt(1e5, 3e6))
        //window.crypto.getRandomValues(array);
        const dummyFile = new Blob([dummyBase, suffixArray])
        zip.file(replay_filename, dummyFile)
      }
    }
  }
  const metaFile = new Blob([JSON.stringify(meta.value)], { type: 'application/json' })
  zip.file('metadata.json', metaFile)

  zip
    .generateAsync({
      type: 'blob',
      comment: zipComment,
      compression: 'DEFLATE',
      compressionOptions: {
        level: 6
      }
    })
    .then(function (blob) {
      saveAs(blob, zipFilename(player1.value, player2.value))
    })
}

const discordMessage = computed(() => {
  const boPaLabel = boPa.value == 'best-of' ? 'Best of' : 'Play all'
  return `${player1.value} || 0 - 0 || ${player2.value}
${boPaLabel} ${games.value.length}
Map draft: ${extractDraftUrl(mapDraft.value)}
Civ draft: ${extractDraftUrl(civDraft.value)}`
})
</script>

<template>
  <Suspense>
    <RecentDrafts
      v-if="mapPresets || civPresets"
      :civ-presets="civPresets"
      :map-presets="mapPresets"
      v-model:map-draft="mapDraft"
      v-model:civ-draft="civDraft"
    />
    <template #fallback>
      <div class="text-center p-4 border-2 col-span-3 mt-4 h-80">Loading Drafts...</div>
    </template>
  </Suspense>
  <GameInfo
    :games="games"
    v-model:player1="player1"
    v-model:player2="player2"
    v-model:map-draft="mapDraft"
    v-model:civ-draft="civDraft"
    :civ-presets="civPresets"
    :map-presets="mapPresets"
    :bo-pa="boPa"
    @update-meta="
      (newErrors: ReplayErrors, newMeta: ReplayMetadata) => {
        if (newMeta?.maps?.pickedMaps?.length) {
          const numOfMaps = newMeta.maps.pickedMaps.length
          if (numOfMaps % 2 == 0) {
            setGames(numOfMaps - 1)
          } else {
            setGames(numOfMaps)
          }
        }
        meta = newMeta
        metaErrors = newErrors
      }
    "
  />
  <SetInfo
    :games-count="games.length"
    @set-games="setGames"
    @set-bo-pa="(newBoPa) => (boPa = newBoPa)"
  />
  <GameBox
    v-for="(game, gameIdx) in games"
    :game="game"
    :key="game.id"
    :game-number="gameIdx"
    @remove-replay="(replayIdx) => removeReplay(gameIdx, replayIdx)"
    @add-replay="addReplay(gameIdx)"
    @update-replay="(replayIdx, file) => updateReplay(gameIdx, replayIdx, file)"
  />
  <div id="message_box" class="mt-4 text-center p-4 border-2 col-span-3 hidden"></div>
  <div class="text-center p-4 border-2 col-span-3 mt-4">
    <ZipPreviewPane :games="games" :player1="player1" :player2="player2" :meta="meta" />
    <button
      :disabled="!downloadEnabled"
      class="btn text-2xl text-white dark:text-black"
      :class="{
        'bg-blue-500': downloadEnabled,
        'bg-blue-200': !downloadEnabled,
        'dark:bg-blue-700': downloadEnabled,
        'dark:bg-blue-300': !downloadEnabled
      }"
      @click="downloadZip"
    >
      Download
    </button>
    <div
      v-if="downloadWarning"
      class="p-2 mt-4 text-sm text-amber-800 rounded-lg bg-amber-100 dark:bg-amber-400 dark:text-amber-800"
    >
      WARNING: You have selected "play all" but not provided all replays.
    </div>
  </div>

  <DiscordMessage :discord-message="discordMessage" />
</template>
