name: Build

on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Build site
        #env:
        #  BASE_URL: '${{ steps.pages.outputs.base_url }}'
        run: npm run build

      - name: Run tests
        run: npm run test:unit
