name: Publish Page

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main', 'beta']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    name: Build Page
    runs-on: ubuntu-latest
    strategy:
      matrix:
        page: [{ branch: 'main', base_url: '' }, { branch: 'beta', base_url: '/beta' }]
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.page.branch }}

      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Build site
        env:
          BASE_URL: '${{ matrix.page.base_url }}'
        #  BASE_URL: '${{ steps.pages.outputs.base_url }}'
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
          name: 'github-pages-${{ matrix.page.branch }}'

  package:
    name: Package pages
    runs-on: ubuntu-latest
    steps:
      - name: Download main artifact
        uses: actions/download-artifact@v4
        with:
          name: 'github-pages-main'

      - name: Download beta artifact
        uses: actions/download-artifact@v4
        with:
          name: 'github-pages-beta'

      - name: Repackage artifacts
        run: |
          mkdir dist
          mkdir dist/beta
          tar -C dist -xf github-pages-main
          tar -C dist/beta -xf github-pages-beta

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Deployment job
  deploy:
    name: Deploy Page
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        # Temp to test that it works
        if: false
        id: deployment
        uses: actions/deploy-pages@v4
